// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamPlaytimeTracker;

#nullable disable

namespace SteamPlaytimeTracker.Migrations
{
    [DbContext(typeof(DbAccess))]
    [Migration("20250826213611_SlimmedTables")]
    partial class SlimmedTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("SteamPlaytimeTracker.DbObject.SteamAppEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LocalApps");
                });

            modelBuilder.Entity("SteamPlaytimeTracker.Steam.Data.App.SteamApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AppId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "appid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("SteamAppEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SteamAppEntryId")
                        .IsUnique();

                    b.ToTable("SteamApps");
                });

            modelBuilder.Entity("SteamPlaytimeTracker.Steam.Data.Playtime.PlaytimeSlice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("SessionLength")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SessionStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("SteamAppEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SteamAppEntryId");

                    b.ToTable("PlaytimeSlices");
                });

            modelBuilder.Entity("SteamPlaytimeTracker.Steam.Data.App.SteamApp", b =>
                {
                    b.HasOne("SteamPlaytimeTracker.DbObject.SteamAppEntry", null)
                        .WithOne("SteamApp")
                        .HasForeignKey("SteamPlaytimeTracker.Steam.Data.App.SteamApp", "SteamAppEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SteamPlaytimeTracker.Steam.Data.Playtime.PlaytimeSlice", b =>
                {
                    b.HasOne("SteamPlaytimeTracker.DbObject.SteamAppEntry", null)
                        .WithMany("PlaytimeSegments")
                        .HasForeignKey("SteamAppEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SteamPlaytimeTracker.DbObject.SteamAppEntry", b =>
                {
                    b.Navigation("PlaytimeSegments");

                    b.Navigation("SteamApp")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
